FROM wazuh/wazuh-manager:4.11.2
COPY custom-rules/custom_rules.xml /var/ossec/etc/rules/
RUN chown wazuh:wazuh /var/ossec/etc/rules/custom_rules.xml && \
    chmod 644 /var/ossec/etc/rules/custom_rules.xml
