name: Wazuh Rule Deployment
on: [push]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Validate Wazuh Rules
        run: |
          cid=$(docker ps|grep "wazuh-manager"|awk '{print $1}')
          docker exec $cid /var/ossec/bin/wazuh-logtest-legacy -t

      - name: Run Unit Tests
        run: |
          cid=$(docker ps|grep "wazuh-manager"|awk '{print $1}')
          docker exec $cid /var/ossec/bin/wazuh-logtest-legacy -t

      - name: Deploy to Wazuh Container
        run: |
          cid=$(docker ps|grep "wazuh-manager"|awk '{print $1}')
          docker cp wazuh-ci-cd/rules/custom_rules.xml $cid:/var/ossec/etc/rules/
          docker exec $cid chown wazuh:wazuh /var/ossec/etc/rules/custom_rules.xml
          docker exec $cid /var/ossec/bin/wazuh-control restart
