name: Wazuh Rule Deployment
on: [push]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Validate Wazuh Rules
        run: |
          docker run --rm -v $(pwd)/rules:/rules wazuh/wazuh-manager:4.11.2 \
          /var/ossec/bin/wazuh-logtest-legacy -t

      - name: Run Unit Tests
        run: |
          docker run --rm -v $(pwd)/rules:/rules wazuh/wazuh-manager:4.11.2 \
          /var/ossec/bin/wazuh-logtest-legacy -t

      - name: Deploy to Wazuh Container
        run: |
          docker cp rules/custom_rules.xml wazuh-manager:/var/ossec/etc/rules/
          docker exec wazuh-manager chown wazuh:wazuh /var/ossec/etc/rules/custom_rules.xml
          docker exec wazuh-manager /var/ossec/bin/wazuh-control restart
