name: Wazuh Rule Deployment
on: [push]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          # instalar la versión clásica (v1) si es necesario:
          sudo curl -L "https://github.com/docker/compose/releases/download/1.26.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Verificar instalación
        run: |
          docker --version
          docker-compose --version  # En nuevas versiones puede ser `docker compose version`

      - name: Start Wazuh with Docker Compose
        run: |
          cd wazuh-ci-cd/single-node
          # docker-compose -f generate-indexer-certs.yml run --rm generator
          # chmod -R 644 config/wazuh_indexer_ssl_certs/*.pem
          docker-compose up -d

      - name: Wait for Wazuh to be healthy
        run: |
          echo "Waiting for wazuh-manager to become healthy..."
          while true; do
            cid=$(docker ps|grep 'wazuh-manager'|awk '{print $1}')
            if [[ -n "$cid" ]]; then  # Verifica si la variable NO está vacía
                break  # Sale del bucle si la variable tiene valor
            fi
            sleep 1  # Espera 1 segundo y reintenta
          done

          for i in {1..20}; do
            status=$(docker inspect --format='{{.State.Status}}' $cid 2>/dev/null || echo "starting")
            echo "Attempt $i: Container health status is '$status'"

            if [ "$status" = "running" ]; then
              echo "Wazuh container is healthy!"
              break
            fi

            if [ "$status" = "exited" ]; then
              echo "Container exited unexpectedly. Failing."
              exit 1
            fi

            sleep 10
          done

      - name: Validate Wazuh Rules
        run: |
          cid=$(docker ps|grep 'wazuh-manager'|awk '{print $1}')
          docker exec $cid /var/ossec/bin/wazuh-logtest-legacy -t

      - name: Run Unit Tests
        run: |
          cid=$(docker ps|grep 'wazuh-manager'|awk '{print $1}')
          docker exec $cid /var/ossec/bin/wazuh-logtest-legacy -t

      - name: Deploy to Wazuh Container
        run: |
          cid=$(docker ps|grep 'wazuh-manager'|awk '{print $1}')
          docker cp wazuh-ci-cd/rules/custom_rules.xml $cid:/var/ossec/etc/rules/
          docker exec $cid chown wazuh:wazuh /var/ossec/etc/rules/custom_rules.xml
          docker exec $cid /var/ossec/bin/wazuh-control restart

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build with Docker Compose, Tag & Push
        run: |
          cd wazuh-ci-cd/single-node/
          ./build.sh
